version: '3'
services:
  localstack:
    container_name: localstack_testing
    image: localstack/localstack
    environment:
      - SERVICES=dynamodb,sqs
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    ports:
      - "4566:4566"
    volumes:
      - /tmp/localstack:/tmp/localstack
